// <auto-generated />
namespace ScheduleApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class mig32720191228 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig32720191228));
        
        string IMigrationMetadata.Id
        {
            get { return "201903271632044_mig32720191228"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
